version: '3'

services:
  httpd:
    container_name: httpd
    restart: unless-stopped
    image: httpd:2.4.41-alpine
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    ports:
      - "80:80"

networks:
  default:
    external:
      name:
        web_network
        